version: "3.8"

services:
  map2adamoint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: map2adamoint-api
    ports:
      - "8085:8085"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
